# Generated by Django 6.0.6 on 2026-06-03 21:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cargos',
            fields=[
                ('id_cargos', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('descripcion', models.CharField(blank=True, max_length=200, null=True)),
                ('salario_base_minimo', models.DecimalField(decimal_places=2, max_digits=12)),
                ('salario_base_maximo', models.DecimalField(decimal_places=2, max_digits=12)),
                ('activo', models.BooleanField(default=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'cargos',
            },
        ),
        migrations.CreateModel(
            name='Departamentos',
            fields=[
                ('id_departamentos', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('descripcion', models.CharField(blank=True, max_length=200, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'departamentos',
            },
        ),
        migrations.CreateModel(
            name='EstadoCivil',
            fields=[
                ('id_estados_civiles', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50, unique=True)),
                ('activo', models.BooleanField(default=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'estados_civiles',
            },
        ),
        migrations.CreateModel(
            name='Genero',
            fields=[
                ('id_generos', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=20)),
                ('activo', models.BooleanField(default=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'generos',
            },
        ),
        migrations.CreateModel(
            name='ModalidadCapacitacion',
            fields=[
                ('id_modalidades_capacitacion', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('activo', models.BooleanField(default=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'modalidades_capacitacion',
            },
        ),
        migrations.CreateModel(
            name='NivelCargo',
            fields=[
                ('id_niveles_cargo', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50, unique=True)),
                ('activo', models.BooleanField(default=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'niveles_cargo',
            },
        ),
        migrations.CreateModel(
            name='ResultadoEvaluacion',
            fields=[
                ('id_resultados_evaluacion', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50, unique=True)),
                ('activo', models.BooleanField(default=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'resultados_evaluacion',
            },
        ),
        migrations.CreateModel(
            name='TipoContrato',
            fields=[
                ('id_tipos_contrato', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('activo', models.BooleanField(default=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'tipos_contrato',
            },
        ),
        migrations.CreateModel(
            name='TipoDocumento',
            fields=[
                ('id_tipos_documento', models.AutoField(primary_key=True, serialize=False)),
                ('codigo', models.CharField(max_length=10, unique=True)),
                ('nombre', models.CharField(max_length=50)),
                ('activo', models.BooleanField(default=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'tipos_documento',
            },
        ),
        migrations.CreateModel(
            name='TipoEvaluacion',
            fields=[
                ('id_tipos_evaluacion', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('activo', models.BooleanField(default=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'tipos_evaluacion',
            },
        ),
        migrations.CreateModel(
            name='Empleados',
            fields=[
                ('id_empleados', models.AutoField(primary_key=True, serialize=False)),
                ('numero_documento', models.CharField(max_length=20, unique=True)),
                ('primer_nombre', models.CharField(max_length=50)),
                ('segundo_nombre', models.CharField(blank=True, max_length=50, null=True)),
                ('primer_apellido', models.CharField(max_length=50)),
                ('segundo_apellido', models.CharField(blank=True, max_length=50, null=True)),
                ('fecha_nacimiento', models.DateField()),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('email_corporativo', models.EmailField(blank=True, max_length=254, null=True, unique=True)),
                ('telefono', models.CharField(max_length=20)),
                ('telefono_emergencia', models.CharField(blank=True, max_length=20, null=True)),
                ('direccion', models.TextField()),
                ('ciudad', models.CharField(max_length=100)),
                ('fecha_ingreso', models.DateField()),
                ('fecha_retiro', models.DateField(blank=True, null=True)),
                ('foto', models.CharField(blank=True, max_length=300, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('id_cargos', models.ForeignKey(db_column='id_cargos', on_delete=django.db.models.deletion.PROTECT, to='api.cargos')),
                ('id_departamentos', models.ForeignKey(db_column='id_departamentos', on_delete=django.db.models.deletion.PROTECT, to='api.departamentos')),
                ('id_estados_civiles', models.ForeignKey(db_column='id_estados_civiles', on_delete=django.db.models.deletion.PROTECT, to='api.estadocivil')),
                ('id_generos', models.ForeignKey(db_column='id_generos', on_delete=django.db.models.deletion.PROTECT, to='api.genero')),
                ('id_tipos_documento', models.ForeignKey(db_column='id_tipos_documento', on_delete=django.db.models.deletion.PROTECT, to='api.tipodocumento')),
            ],
            options={
                'db_table': 'empleados',
            },
        ),
        migrations.CreateModel(
            name='Estado',
            fields=[
                ('id_estados', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('contexto', models.CharField(choices=[('CONTRATO', 'Contrato'), ('NOMINA', 'Nómina'), ('VACACIONES', 'Vacaciones'), ('CAPACITACION', 'Capacitación')], max_length=15)),
                ('activo', models.BooleanField(default=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'estados',
                'unique_together': {('nombre', 'contexto')},
            },
        ),
        migrations.CreateModel(
            name='Capacitaciones',
            fields=[
                ('id_capacitaciones', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('proveedor', models.CharField(blank=True, max_length=150, null=True)),
                ('duracion_horas', models.SmallIntegerField()),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('lugar', models.CharField(blank=True, max_length=200, null=True)),
                ('costo', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('calificacion', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('aprobado', models.BooleanField(default=False)),
                ('url_certificado', models.CharField(blank=True, max_length=300, null=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('id_empleados', models.ForeignKey(db_column='id_empleados', on_delete=django.db.models.deletion.PROTECT, to='api.empleados')),
                ('id_estados', models.ForeignKey(db_column='id_estados', limit_choices_to={'contexto': 'CAPACITACION'}, on_delete=django.db.models.deletion.PROTECT, to='api.estado')),
                ('id_modalidades_capacitacion', models.ForeignKey(db_column='id_modalidades_capacitacion', on_delete=django.db.models.deletion.PROTECT, to='api.modalidadcapacitacion')),
            ],
            options={
                'db_table': 'capacitaciones',
            },
        ),
        migrations.AddField(
            model_name='cargos',
            name='id_niveles_cargo',
            field=models.ForeignKey(db_column='id_niveles_cargo', on_delete=django.db.models.deletion.PROTECT, to='api.nivelcargo'),
        ),
        migrations.CreateModel(
            name='Contratos',
            fields=[
                ('id_contratos', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField(blank=True, null=True)),
                ('salario', models.DecimalField(decimal_places=2, max_digits=12)),
                ('jornada_horas', models.SmallIntegerField(default=8)),
                ('url_documento', models.CharField(blank=True, max_length=300, null=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('id_empleados', models.ForeignKey(db_column='id_empleados', on_delete=django.db.models.deletion.PROTECT, to='api.empleados')),
                ('id_estados', models.ForeignKey(db_column='id_estados', limit_choices_to={'contexto': 'CONTRATO'}, on_delete=django.db.models.deletion.PROTECT, to='api.estado')),
                ('id_tipos_contrato', models.ForeignKey(db_column='id_tipos_contrato', on_delete=django.db.models.deletion.PROTECT, to='api.tipocontrato')),
            ],
            options={
                'db_table': 'contratos',
            },
        ),
        migrations.CreateModel(
            name='Evaluaciones',
            fields=[
                ('id_evaluaciones', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_evaluacion', models.DateField()),
                ('periodo_evaluado_inicio', models.DateField()),
                ('periodo_evaluado_fin', models.DateField()),
                ('puntualidad', models.SmallIntegerField()),
                ('productividad', models.SmallIntegerField()),
                ('trabajo_equipo', models.SmallIntegerField()),
                ('calidad_trabajo', models.SmallIntegerField()),
                ('liderazgo', models.SmallIntegerField(default=0)),
                ('puntaje_total', models.DecimalField(decimal_places=2, max_digits=5)),
                ('fortalezas', models.TextField(blank=True, null=True)),
                ('areas_mejora', models.TextField(blank=True, null=True)),
                ('plan_accion', models.TextField(blank=True, null=True)),
                ('comentarios_empleado', models.TextField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('id_empleados', models.ForeignKey(db_column='id_empleados', on_delete=django.db.models.deletion.PROTECT, related_name='evaluaciones', to='api.empleados')),
                ('id_evaluador', models.ForeignKey(db_column='id_evaluador', on_delete=django.db.models.deletion.PROTECT, related_name='evaluaciones_realizadas', to='api.empleados')),
                ('id_resultados_evaluacion', models.ForeignKey(db_column='id_resultados_evaluacion', on_delete=django.db.models.deletion.PROTECT, to='api.resultadoevaluacion')),
                ('id_tipos_evaluacion', models.ForeignKey(db_column='id_tipos_evaluacion', on_delete=django.db.models.deletion.PROTECT, to='api.tipoevaluacion')),
            ],
            options={
                'db_table': 'evaluaciones',
            },
        ),
        migrations.CreateModel(
            name='Vacaciones',
            fields=[
                ('id_vacaciones', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('dias_solicitados', models.SmallIntegerField()),
                ('dias_habiles', models.SmallIntegerField()),
                ('fecha_aprobacion', models.DateTimeField(blank=True, null=True)),
                ('motivo_rechazo', models.TextField(blank=True, null=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('id_aprobado_por', models.ForeignKey(blank=True, db_column='id_aprobado_por', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vacaciones_aprobadas', to='api.empleados')),
                ('id_empleados', models.ForeignKey(db_column='id_empleados', on_delete=django.db.models.deletion.PROTECT, related_name='vacaciones', to='api.empleados')),
                ('id_estados', models.ForeignKey(db_column='id_estados', limit_choices_to={'contexto': 'VACACIONES'}, on_delete=django.db.models.deletion.PROTECT, to='api.estado')),
            ],
            options={
                'db_table': 'vacaciones',
            },
        ),
        migrations.CreateModel(
            name='Nomina',
            fields=[
                ('id_nomina', models.AutoField(primary_key=True, serialize=False)),
                ('periodo_inicio', models.DateField()),
                ('periodo_fin', models.DateField()),
                ('salario_base', models.DecimalField(decimal_places=2, max_digits=12)),
                ('horas_extras', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('bonificaciones', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('auxilio_transporte', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('otros_devengados', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_devengado', models.DecimalField(decimal_places=2, max_digits=12)),
                ('salud', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('pension', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('retencion_fuente', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('otras_deducciones', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_deducciones', models.DecimalField(decimal_places=2, max_digits=12)),
                ('neto_pagado', models.DecimalField(decimal_places=2, max_digits=12)),
                ('fecha_pago', models.DateField(blank=True, null=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('id_empleados', models.ForeignKey(db_column='id_empleados', on_delete=django.db.models.deletion.PROTECT, to='api.empleados')),
                ('id_estados', models.ForeignKey(db_column='id_estados', limit_choices_to={'contexto': 'NOMINA'}, on_delete=django.db.models.deletion.PROTECT, to='api.estado')),
            ],
            options={
                'db_table': 'nomina',
                'unique_together': {('id_empleados', 'periodo_inicio', 'periodo_fin')},
            },
        ),
    ]
